// Courses module - handles course data and rendering

// Factory function for creating course data with consistent structure
function createCourse(id, name, subtitle, emoji, gradientStart, gradientEnd, targetColor, targetText, objectiveText, readingText, speakingText, writingText, targetScoreText) {
    return {
        id,
        name,
        subtitle,
        emoji,
        gradientStart,
        gradientEnd,
        targetTitle: "Dành cho:",
        targetText,
        targetColor,
        objectiveTitle: objectiveText.includes("Mục tiêu") ? "Mục tiêu:" : "Yêu cầu:",
        objectiveText,
        objectiveColor: targetColor,
        readingTitle: "📚 Reading & Listening",
        readingText,
        readingColor: targetColor,
        speakingTitle: "🗣️ Speaking",
        speakingText,
        speakingColor: targetColor,
        writingTitle: "✍️ Writing",
        writingText,
        writingColor: targetColor,
        targetScoreTitle: "🎯 Target",
        targetScoreText,
        targetScoreColor: targetColor
    };
}

// Course data structure
const courseData = [
    {
        id: "candy",
        name: "Level Candy",
        subtitle: "Beginner Level - IELTS Foundation",
        emoji: "🍭",
        gradientStart: "green",
        gradientEnd: "blue",
        targetTitle: "Dành cho:",
        targetText: "Không dành cho vỡ lòng, mất gốc, mất căn bản. Dành cho những bạn chưa làm quen với IELTS, chưa tiếp xúc nhiều với tiếng Anh.",
        targetColor: "pink",
        objectiveTitle: "Mục tiêu:",
        objectiveText: "Định hướng, giới thiệu về IELTS. Tập trung ôn lại một số chủ điểm ngữ pháp chính, bổ sung từ vựng cơ bản theo chủ đề, từ vựng về IELTS.",
        objectiveColor: "pink",
        readingTitle: "📚 Reading & Listening",
        readingText: "Làm quen các bài đơn giản, đoạn văn ngắn, tập phân tích, hiểu yêu cầu đề bài",
        readingColor: "pink",
        speakingTitle: "🗣️ Speaking",
        speakingText: "Làm quen với câu hỏi đơn giản, tập trung vào phát triển ý, phát âm và phản xạ",
        speakingColor: "pink",
        writingTitle: "✍️ Writing",
        writingText: "Tập viết câu hoàn chỉnh, tập triển khai ý. Phân biệt được văn nói và văn viết trong IELTS",
        writingColor: "pink",
        targetScoreTitle: "🎯 Target",
        targetScoreText: "Band 2.5 - Nền tảng vững chắc cho các level tiếp theo",
        targetScoreColor: "pink"
    },
    {
        id: "cookies",
        name: "Level Cookies",
        subtitle: "Elementary Level - IELTS Introduction",
        emoji: "🍪",
        gradientStart: "blue",
        gradientEnd: "indigo",
        targetTitle: "Dành cho:",
        targetText: "Những bạn đã từng học IELTS dưới 3 tháng (điểm test đầu vào từ 3.0+) hoặc học viên đã qua level Candy.",
        targetColor: "orange",
        objectiveTitle: "Mục tiêu:",
        objectiveText: "Các bạn bắt đầu tiếp xúc format IELTS, làm quen các dạng bài ở các kỹ năng.",
        objectiveColor: "orange",
        readingTitle: "📚 Reading & Listening",
        readingText: "Làm các dạng bài ngắn, tập trung vào phân tích bài và nâng cấp từ vựng",
        readingColor: "orange",
        speakingTitle: "🗣️ Speaking",
        speakingText: "Luyện nói chủ đề đời sống quen thuộc, tập trung vào phát triển ý theo format IELTS",
        speakingColor: "orange",
        writingTitle: "✍️ Writing",
        writingText: "Làm quen với lý thuyết Viết: biểu đồ Task 1 và các dạng bài Task 2",
        writingColor: "orange",
        targetScoreTitle: "🎯 Target",
        targetScoreText: "Band 3.5 - Hiểu rõ format và cách làm bài IELTS",
        targetScoreColor: "orange"
    },
    {
        id: "donuts",
        name: "Level Donuts",
        subtitle: "Intermediate Level - IELTS Progress",
        emoji: "🍩",
        gradientStart: "indigo",
        gradientEnd: "purple",
        targetTitle: "Dành cho:",
        targetText: "Những bạn đã từng học IELTS (điểm test đầu vào từ 4.0+) hoặc học viên đã qua level Cookies.",
        targetColor: "indigo",
        objectiveTitle: "Yêu cầu:",
        objectiveText: "Các bạn đã có kiến thức cơ bản IELTS và các dạng bài (level này vẫn ôn lại lý thuyết Viết).",
        objectiveColor: "indigo",
        readingTitle: "📚 Reading & Listening",
        readingText: "Bắt đầu làm các bài dài và thử thách hơn, đẩy mạnh kỹ năng phân tích bài",
        readingColor: "indigo",
        speakingTitle: "🗣️ Speaking",
        speakingText: "Luyện nói chủ đề quen thuộc, tăng cường phát âm và phản xạ, nâng cao từ vựng B1&B2",
        speakingColor: "indigo",
        writingTitle: "✍️ Writing",
        writingText: "Luyện viết các dạng biểu đồ Task 1 và Task 2, đẩy mạnh kỹ năng phân tích và lập dàn ý",
        writingColor: "indigo",
        targetScoreTitle: "🎯 Target",
        targetScoreText: "Band 4.5 - Thành thạo các kỹ năng IELTS cơ bản",
        targetScoreColor: "indigo"
    },
    {
        id: "bagels",
        name: "Level Bagels",
        subtitle: "Upper Intermediate - IELTS Mastery",
        emoji: "🥯",
        gradientStart: "purple",
        gradientEnd: "pink",
        targetTitle: "Dành cho:",
        targetText: "Những bạn đã từng học IELTS (điểm test đầu vào từ 4.5+) hoặc học viên đã qua level Donuts.",
        targetColor: "teal",
        objectiveTitle: "Yêu cầu:",
        objectiveText: "Các bạn đã có nền tảng về IELTS và muốn nâng cao kỹ năng để đạt điểm cao hơn.",
        objectiveColor: "teal",
        readingTitle: "📚 Reading & Listening",
        readingText: "Làm quen với các bài đọc và nghe dài, độ khó tăng dần, đẩy mạnh từ vựng học thuật",
        readingColor: "teal",
        speakingTitle: "🗣️ Speaking",
        speakingText: "Luyện tập với các chủ đề phong phú, phát triển ý logic, nâng cao phát âm",
        speakingColor: "teal",
        writingTitle: "✍️ Writing",
        writingText: "Luyện viết theo format chuẩn, đẩy mạnh kỹ năng lập luận, sử dụng từ vựng nâng cao",
        writingColor: "teal",
        targetScoreTitle: "🎯 Target",
        targetScoreText: "Band 5.0+ - Nâng cao và tinh chỉnh các kỹ năng IELTS",
        targetScoreColor: "teal"
    },
    {
        id: "burgers",
        name: "Level Burgers",
        subtitle: "Advanced Level - IELTS Excellence",
        emoji: "🍔",
        gradientStart: "pink",
        gradientEnd: "red",
        targetTitle: "Dành cho:",
        targetText: "Những bạn đã từng học IELTS (điểm test đầu vào 5.0+) hoặc học viên đã qua level Donuts.",
        targetColor: "red",
        objectiveTitle: "Yêu cầu:",
        objectiveText: "Các bạn đã nắm chắc kiến thức IELTS và kỹ năng làm bài cơ bản ở các kỹ năng.",
        objectiveColor: "red",
        readingTitle: "📚 Reading & Listening",
        readingText: "Luyện đề thi thật, đẩy mạnh kỹ năng phân tích bài và nâng từ vựng, áp lực thời gian",
        readingColor: "red",
        speakingTitle: "🗣️ Speaking",
        speakingText: "Luyện nói chủ đề mới, phong phú hơn, đẩy mạnh phát âm, phản xạ và phát triển ý",
        speakingColor: "red",
        writingTitle: "✍️ Writing",
        writingText: "Viết thành thạo các dạng bài, đẩy mạnh kỹ năng phân tích, áp dụng cấu trúc phức tạp",
        writingColor: "red",
        targetScoreTitle: "🎯 Target",
        targetScoreText: "Band 5.5+ - Đạt điểm cao và chuẩn bị cho các level nâng cao",
        targetScoreColor: "red"
    },
    {
        id: "pizzas",
        name: "Level Pizzas",
        subtitle: "Expert Level - IELTS Perfection",
        emoji: "🍕",
        gradientStart: "red",
        gradientEnd: "orange",
        targetTitle: "Dành cho:",
        targetText: "Những bạn đã có nền tảng vững chắc về IELTS (điểm test đầu vào từ 6.0+) hoặc học viên đã qua level Burgers.",
        targetColor: "cyan",
        objectiveTitle: "Yêu cầu:",
        objectiveText: "Các bạn đã quen với format bài thi và muốn tối ưu hóa chiến lược làm bài để đạt band cao hơn.",
        objectiveColor: "cyan",
        readingTitle: "📚 Reading & Listening",
        readingText: "Luyện đề nâng cao, làm quen với nội dung học thuật chuyên sâu, phát triển kỹ năng scan, skim",
        readingColor: "cyan",
        speakingTitle: "🗣️ Speaking",
        speakingText: "Luyện tập với các chủ đề học thuật và trừu tượng, đẩy mạnh khả năng phát triển ý",
        speakingColor: "cyan",
        writingTitle: "✍️ Writing",
        writingText: "Luyện viết các dạng bài nâng cao, tối ưu hóa bố cục bài viết, sử dụng từ vựng học thuật",
        writingColor: "cyan",
        targetScoreTitle: "🎯 Target",
        targetScoreText: "Band 6.5+ - Đạt điểm cao trong kỳ thi IELTS",
        targetScoreColor: "cyan"
    },
    {
        id: "intensive",
        name: "Level Intensive",
        subtitle: "Elite Level - IELTS Conqueror",
        emoji: "🚀",
        gradientStart: "orange",
        gradientEnd: "orange",
        targetTitle: "Dành cho:",
        targetText: "Những bạn đã đăng ký thi IELTS trong quý và đã qua bài Mock Test từ 4.5+ trở lên (tuỳ theo đầu ra để chọn những đầu vào phù hợp).",
        targetColor: "yellow",
        objectiveTitle: "",
        objectiveText: "",
        objectiveColor: "yellow",
        readingTitle: "👨‍🏫 Expert Coaching",
        readingText: "Học viên được luyện tập với đề thi thật IELTS cùng giáo viên kinh nghiệm nhiều năm",
        readingColor: "yellow",
        speakingTitle: "📊 Mock Tests",
        speakingText: "Tổ chức thi thử, đưa ra đánh giá chi tiết điểm số cho 4 tiêu chí của IELTS",
        speakingColor: "yellow",
        writingTitle: "💻 E-learning",
        writingText: "Học viên được sử dụng hệ thống E-learning của STUDIO để trả bài tập về nhà",
        writingColor: "yellow",
        targetScoreTitle: "🎯 Exam Ready",
        targetScoreText: "Chuẩn bị tâm lý trước khi thi, luyện tập theo thể thức thi thực tế",
        targetScoreColor: "yellow"
    }
];

// Export for global use
window.createCourse = createCourse;
window.courseData = courseData;